string episode_id
string waypoint
string meta_data
uint32 timestamp

tf/tfMessage transform
sensor_msgs/PointCloud2 cloud
sensor_msgs/Image rgb_img
sensor_msgs/Image depth_img
sensor_msgs/CameraInfo camera_info
geometry_msgs/Pose robot_pose
---
bool result
soma_llsd_msgs/Scene response
